version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  app:
    container_name: makeup_container
    image: novakvova/makeup-asp-api
    ports:
      - "5817:8080"  
    networks:
      - myAppNetwork
    environment:
      - DefaultConnection=Server=ep-long-firefly-a2qp0hj6-pooler.eu-central-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_wQjgN89tVlTc
    volumes:
      - /volumes/makeup-asp/backup:/app/backup 
      - /volumes/makeup-asp/images:/app/uploading
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  client:
    container_name: makeup_client_container
    image: novakvova/makeup-client
    restart: on-failure
    ports:
      - "5092:80"  
    networks:
      - myAppNetwork
