version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  db:
    container_name: pg-container
    image: postgres:17
    environment:
      POSTGRES_USER: krot
      POSTGRES_PASSWORD: p%rSDj4Imds0763300sfgs7djc**dmUntdOidd3dZ_#WTi4B9Zo
      POSTGRES_DB: cosmeria
    volumes:
      - /volumes/postgres01/data:/var/lib/makeup/data
    ports:
      - "5432:5432"
    networks:
      - myAppNetwork
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
  app:
    container_name: makeup_container
    image: novakvova/makeup-asp-api
    ports:
      - "5817:8080"  
    networks:
      - myAppNetwork
    environment:
        ConnectionStrings__DefaultConnection: "Host=db;Database=cosmeria;Username=krot;Password=p%rSDj4Imds0763300sfgs7djc**dmUntdOidd3dZ_#WTi4B9Zo"
        Cors__AllowedOrigins: "http://172.19.111.201:5092"
    volumes:
      - /volumes/makeup-asp/images:/app/uploading
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  client:
    container_name: makeup_client_container
    image: novakvova/makeup-client
    restart: on-failure
    ports:
      - "5092:80"  
    networks:
      - myAppNetwork
